CREATE TABLE occ_departments
(
  DEPARTMENT_ID         NUMBER(5)         GENERATED BY DEFAULT AS IDENTITY  NOT NULL ,
  DEPARTMENT_NAME       VARCHAR2(50 CHAR)                                   NOT NULL,
  LOCATION              VARCHAR2(50 CHAR)                                   NOT NULL,
  CREATED_BY            VARCHAR2(50 CHAR) DEFAULT USER                      NOT NULL,
  DATE_CREATED          DATE              DEFAULT SYSDATE                   NOT NULL,
  UPDATED_BY            VARCHAR2(50 CHAR)                                       NULL,
  DATE_UPDATED          DATE                                                    NULL
);

COMMENT ON TABLE occ_departments IS 'Departments';

COMMENT ON COLUMN occ_departments.DEPARTMENT_ID   IS 'The unique identifier for the department';
COMMENT ON COLUMN occ_departments.DEPARTMENT_NAME IS 'The name of the department';
COMMENT ON COLUMN occ_departments.LOCATION        IS 'The physical location of the department';
COMMENT ON COLUMN occ_departments.CREATED_BY      IS 'Creator of the record';
COMMENT ON COLUMN occ_departments.DATE_CREATED    IS 'Date record created';
COMMENT ON COLUMN occ_departments.UPDATED_BY      IS 'Last user who updated the record';
COMMENT ON COLUMN occ_departments.DATE_UPDATED    IS 'Date record last updated';

CREATE UNIQUE INDEX DEPARTMENT_PK ON occ_departments (DEPARTMENT_ID);
CREATE UNIQUE INDEX DEPARTMENT_UK ON occ_departments (DEPARTMENT_NAME);

ALTER TABLE occ_departments ADD 
 (CONSTRAINT DEPARTMENT_PK
  PRIMARY KEY (DEPARTMENT_ID)
  USING INDEX DEPARTMENT_PK
  ENABLE 
  VALIDATE,  
  CONSTRAINT DEPARTMENT_UK
  UNIQUE (DEPARTMENT_NAME)
  USING INDEX DEPARTMENT_UK
  ENABLE 
  VALIDATE);

CREATE OR REPLACE PUBLIC SYNONYM occ_departments FOR occ_departments;

CREATE TABLE occ_employees
(
  EMPLOYEE_ID            NUMBER(5)         GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  EMPLOYEE_NAME          VARCHAR2(50 CHAR)                                  NOT NULL,
  JOB_TITLE              VARCHAR2(50 CHAR)                                  NOT NULL,
  DATE_HIRED             DATE                                               NOT NULL,
  SALARY                 NUMBER(10)                                         NOT NULL,
  DEPARTMENT_ID          NUMBER(10)                                         NOT NULL,
  MANAGER_ID             NUMBER(5 )                                             NULL,
  CREATED_BY             VARCHAR2(50 CHAR) DEFAULT USER                     NOT NULL,
  DATE_CREATED           DATE              DEFAULT SYSDATE                  NOT NULL,
  UPDATED_BY             VARCHAR2(50 CHAR)                                      NULL,
  DATE_UPDATED           DATE                                                   NULL
);

COMMENT ON TABLE occ_employees IS 'Employees';

COMMENT ON COLUMN occ_employees.EMPLOYEE_ID   IS 'The unique identifier for the employee';
COMMENT ON COLUMN occ_employees.EMPLOYEE_NAME IS 'The name of the employee';
COMMENT ON COLUMN occ_employees.JOB_TITLE     IS 'The job role undertaken by the employee';
COMMENT ON COLUMN occ_employees.DATE_HIRED    IS 'The date the employee was hired';
COMMENT ON COLUMN occ_employees.SALARY        IS 'Current salary of the employee';
COMMENT ON COLUMN occ_employees.DEPARTMENT_ID IS 'Department of the employee';
COMMENT ON COLUMN occ_employees.MANAGER_ID    IS 'Line manager of the employee';
COMMENT ON COLUMN occ_employees.CREATED_BY    IS 'Creator of the record';
COMMENT ON COLUMN occ_employees.DATE_CREATED  IS 'Date record created';
COMMENT ON COLUMN occ_employees.UPDATED_BY    IS 'Last user who updated the record';
COMMENT ON COLUMN occ_employees.DATE_UPDATED  IS 'Date record last updated';

CREATE UNIQUE INDEX EMPLOYEE_PK ON occ_employees (EMPLOYEE_ID);

ALTER TABLE occ_employees ADD 
 (CONSTRAINT EMPLOYEE_PK
  PRIMARY KEY
  (EMPLOYEE_ID)
  USING INDEX EMPLOYEE_PK
  ENABLE VALIDATE);

CREATE INDEX EMPLOYEE_DEPARTMENT_FK_I ON occ_employees (DEPARTMENT_ID);
CREATE INDEX EMPLOYEE_MANAGER_FK_I    ON occ_employees (MANAGER_ID);

ALTER TABLE occ_employees ADD (
  CONSTRAINT EMPLOYEE_DEPARTMENT_FK 
  FOREIGN KEY (DEPARTMENT_ID) 
  REFERENCES occ_departments (DEPARTMENT_ID)
  ENABLE VALIDATE,
  CONSTRAINT EMPLOYEE_MANAGER_FK 
  FOREIGN KEY (MANAGER_ID) 
  REFERENCES occ_employees (EMPLOYEE_ID)
  DEFERRABLE INITIALLY DEFERRED
  ENABLE VALIDATE);

CREATE OR REPLACE PUBLIC SYNONYM occ_employees FOR occ_employees;



